clang -emit-llvm -O0 -c -g -I . ./e_acos.c -o ./e_acos_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_acosh.c -o ./e_acosh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_asin.c -o ./e_asin_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_atan2.c -o ./e_atan2_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_atanh.c -o ./e_atanh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_cosh.c -o ./e_cosh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_exp.c -o ./e_exp_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_fmod.c -o ./e_fmod_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_gamma.c -o ./e_gamma_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_gamma_r.c -o ./e_gamma_r_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_hypot.c -o ./e_hypot_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_j0.c -o ./e_j0_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_j1.c -o ./e_j1_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_jn.c -o ./e_jn_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_lgamma.c -o ./e_lgamma_float_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_lgamma_r.c -o ./e_lgamma_r_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_log.c -o ./e_log_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_log10.c -o ./e_log10_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_pow.c -o ./e_pow_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_rem_pio2.c -o ./e_rem_pio2_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_remainder.c -o ./e_remainder_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_scalb.c -o ./e_scalb_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_sinh.c -o ./e_sinh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_sqrt.c -o ./e_sqrt_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./k_cos.c -o ./k_cos_float.bc -lm
# SKIP (blacklisted): k_rem_pio2.c
clang -emit-llvm -O0 -c -g -I . ./k_sin.c -o ./k_sin_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./k_standard.c -o ./k_standard_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./k_tan.c -o ./k_tan_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_asinh.c -o ./s_asinh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_atan.c -o ./s_atan_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_cbrt.c -o ./s_cbrt_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_ceil.c -o ./s_ceil_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_copysign.c -o ./s_copysign_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_cos.c -o ./s_cos_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_erf.c -o ./s_erf_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_expm1.c -o ./s_expm1_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_fabs.c -o ./s_fabs_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_finite.c -o ./s_finite_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_floor.c -o ./s_floor_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_frexp.c -o ./s_frexp_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_ilogb.c -o ./s_ilogb_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_isnan.c -o ./s_isnan_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_ldexp.c -o ./s_ldexp_float.bc -lm
# SKIP (blacklisted): s_lib_version.c
clang -emit-llvm -O0 -c -g -I . ./s_log1p.c -o ./s_log1p_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_logb.c -o ./s_logb_float.bc -lm
# SKIP (blacklisted): s_matherr.c
clang -emit-llvm -O0 -c -g -I . ./s_modf.c -o ./s_modf_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_nextafter.c -o ./s_nextafter_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_rint.c -o ./s_rint_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_scalbn.c -o ./s_scalbn_float.bc -lm
# SKIP (blacklisted): s_signgam.c
clang -emit-llvm -O0 -c -g -I . ./s_significand.c -o ./s_significand_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_sin.c -o ./s_sin_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_tan.c -o ./s_tan_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_tanh.c -o ./s_tanh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_acos.c -o ./w_acos_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_acosh.c -o ./w_acosh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_asin.c -o ./w_asin_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_atan2.c -o ./w_atan2_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_atanh.c -o ./w_atanh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_cosh.c -o ./w_cosh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_exp.c -o ./w_exp_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_fmod.c -o ./w_fmod_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_gamma.c -o ./w_gamma_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_gamma_r.c -o ./w_gamma_r_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_hypot.c -o ./w_hypot_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_j0.c -o ./w_j0_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_j1.c -o ./w_j1_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_jn.c -o ./w_jn_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_lgamma.c -o ./w_lgamma_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_lgamma_r.c -o ./w_lgamma_r_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_log.c -o ./w_log_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_log10.c -o ./w_log10_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_pow.c -o ./w_pow_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_remainder.c -o ./w_remainder_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_scalb.c -o ./w_scalb_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_sinh.c -o ./w_sinh_float.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_sqrt.c -o ./w_sqrt_float.bc -lm
