clang -emit-llvm -O0 -c -g -I . ./e_acos.c -o ./e_acos.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_acosh.c -o ./e_acosh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_asin.c -o ./e_asin.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_atan2.c -o ./e_atan2.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_atanh.c -o ./e_atanh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_cosh.c -o ./e_cosh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_exp.c -o ./e_exp.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_fmod.c -o ./e_fmod.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_gamma.c -o ./e_gamma.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_gamma_r.c -o ./e_gamma_r.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_hypot.c -o ./e_hypot.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_j0.c -o ./e_j0.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_j1.c -o ./e_j1.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_jn.c -o ./e_jn.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_lgamma.c -o ./e_lgamma.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_lgamma_r.c -o ./e_lgamma_r.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_log.c -o ./e_log.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_log10.c -o ./e_log10.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_pow.c -o ./e_pow.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_rem_pio2.c -o ./e_rem_pio2.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_remainder.c -o ./e_remainder.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_scalb.c -o ./e_scalb.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_sinh.c -o ./e_sinh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./e_sqrt.c -o ./e_sqrt.bc -lm
clang -emit-llvm -O0 -c -g -I . ./k_cos.c -o ./k_cos.bc -lm
# SKIP (blacklisted): k_rem_pio2.c
clang -emit-llvm -O0 -c -g -I . ./k_sin.c -o ./k_sin.bc -lm
clang -emit-llvm -O0 -c -g -I . ./k_standard.c -o ./k_standard.bc -lm
clang -emit-llvm -O0 -c -g -I . ./k_tan.c -o ./k_tan.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_asinh.c -o ./s_asinh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_atan.c -o ./s_atan.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_cbrt.c -o ./s_cbrt.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_ceil.c -o ./s_ceil.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_copysign.c -o ./s_copysign.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_cos.c -o ./s_cos.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_erf.c -o ./s_erf.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_expm1.c -o ./s_expm1.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_fabs.c -o ./s_fabs.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_finite.c -o ./s_finite.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_floor.c -o ./s_floor.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_frexp.c -o ./s_frexp.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_ilogb.c -o ./s_ilogb.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_isnan.c -o ./s_isnan.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_ldexp.c -o ./s_ldexp.bc -lm
# SKIP (blacklisted): s_lib_version.c
clang -emit-llvm -O0 -c -g -I . ./s_log1p.c -o ./s_log1p.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_logb.c -o ./s_logb.bc -lm
# SKIP (blacklisted): s_matherr.c
clang -emit-llvm -O0 -c -g -I . ./s_modf.c -o ./s_modf.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_nextafter.c -o ./s_nextafter.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_rint.c -o ./s_rint.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_scalbn.c -o ./s_scalbn.bc -lm
# SKIP (blacklisted): s_signgam.c
clang -emit-llvm -O0 -c -g -I . ./s_significand.c -o ./s_significand.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_sin.c -o ./s_sin.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_tan.c -o ./s_tan.bc -lm
clang -emit-llvm -O0 -c -g -I . ./s_tanh.c -o ./s_tanh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_acos.c -o ./w_acos.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_acosh.c -o ./w_acosh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_asin.c -o ./w_asin.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_atan2.c -o ./w_atan2.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_atanh.c -o ./w_atanh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_cosh.c -o ./w_cosh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_exp.c -o ./w_exp.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_fmod.c -o ./w_fmod.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_gamma.c -o ./w_gamma.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_gamma_r.c -o ./w_gamma_r.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_hypot.c -o ./w_hypot.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_j0.c -o ./w_j0.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_j1.c -o ./w_j1.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_jn.c -o ./w_jn.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_lgamma.c -o ./w_lgamma.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_lgamma_r.c -o ./w_lgamma_r.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_log.c -o ./w_log.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_log10.c -o ./w_log10.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_pow.c -o ./w_pow.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_remainder.c -o ./w_remainder.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_scalb.c -o ./w_scalb.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_sinh.c -o ./w_sinh.bc -lm
clang -emit-llvm -O0 -c -g -I . ./w_sqrt.c -o ./w_sqrt.bc -lm
