#!/usr/bin/env bash
set -euo pipefail
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_acos.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_acos.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_acosh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_acosh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_asin.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_asin.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_atan2.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_atan2.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_atanh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_atanh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_cosh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_cosh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_exp.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_exp.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_fmod.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_fmod.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_gamma.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_gamma.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_gamma_r.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_gamma_r.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_hypot.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_hypot.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_j0.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_j0.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_j1.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_j1.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_jn.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_jn.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_lgamma_float.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_lgamma_float.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_lgamma_r.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_lgamma_r.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_log.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_log.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_log10.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_log10.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_pow.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_pow.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_rem_pio2.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_rem_pio2.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_remainder.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_remainder.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_scalb.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_scalb.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_sinh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_sinh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/e_sqrt.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/e_sqrt.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/k_cos.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/k_cos.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/k_sin.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/k_sin.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/k_standard.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/k_standard.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/k_tan.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/k_tan.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_asinh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_asinh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_atan.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_atan.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_cbrt.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_cbrt.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_ceil.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_ceil.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_copysign.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_copysign.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_cos.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_cos.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_erf.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_erf.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_expm1.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_expm1.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_fabs.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_fabs.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_finite.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_finite.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_floor.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_floor.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_frexp.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_frexp.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_ilogb.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_ilogb.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_isnan.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_isnan.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_ldexp.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_ldexp.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_log1p.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_log1p.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_logb.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_logb.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_modf.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_modf.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_nextafter.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_nextafter.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_rint.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_rint.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_scalbn.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_scalbn.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_significand.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_significand.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_sin.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_sin.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_tan.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_tan.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/s_tanh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/s_tanh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_acos.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_acos.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_acosh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_acosh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_asin.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_asin.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_atan2.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_atan2.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_atanh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_atanh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_cosh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_cosh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_exp.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_exp.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_fmod.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_fmod.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_gamma.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_gamma.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_gamma_r.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_gamma_r.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_hypot.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_hypot.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_j0.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_j0.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_j1.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_j1.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_jn.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_jn.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_lgamma.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_lgamma.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_lgamma_r.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_lgamma_r.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_log.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_log.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_log10.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_log10.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_pow.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_pow.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_remainder.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_remainder.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_scalb.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_scalb.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_sinh.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_sinh.c z3 900 results_fdlibm_simple_z3_linked.json
./run_bc_fdlibm.sh /home/klee/logic_bombs/fdlibm/fdlibm_main_simple/w_sqrt.bc /home/klee/logic_bombs/fdlibm/fdlibm_simple/w_sqrt.c z3 900 results_fdlibm_simple_z3_linked.json
