#!/usr/bin/env bash
set -euo pipefail

./run_bc_klee_fdlibm_simple.sh ./e_acos_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_acosh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_asin_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_atan2_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_atanh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_cosh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_exp_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_fmod_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_gamma_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_gamma_r_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_hypot_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_j0_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_j1_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_jn_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_lgamma_float_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_lgamma_r_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_log_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_log10_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_pow_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_rem_pio2_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_remainder_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_scalb_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_sinh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./e_sqrt_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./k_cos_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./k_sin_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./k_standard_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./k_tan_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_asinh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_atan_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_cbrt_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_ceil_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_copysign_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_cos_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_erf_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_expm1_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_fabs_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_finite_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_floor_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_frexp_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_ilogb_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_isnan_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_ldexp_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_log1p_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_logb_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_modf_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_nextafter_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_rint_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_scalbn_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_significand_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_sin_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_tan_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./s_tanh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_acos_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_acosh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_asin_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_atan2_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_atanh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_cosh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_exp_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_fmod_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_gamma_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_gamma_r_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_hypot_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_j0_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_j1_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_jn_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_lgamma_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_lgamma_r_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_log_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_log10_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_pow_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_remainder_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_scalb_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_sinh_float.bc z3 900 results_fdlibm_float_z3.json
./run_bc_klee_fdlibm_simple.sh ./w_sqrt_float.bc z3 900 results_fdlibm_float_z3.json
