#!/usr/bin/env bash
set -euo pipefail

./run_bc_klee_fdlibm_simple.sh ./e_acos.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_acosh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_asin.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_atan2.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_atanh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_cosh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_exp.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_fmod.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_gamma.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_gamma_r.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_hypot.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_j0.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_j1.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_jn.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_lgamma.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_lgamma_r.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_log.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_log10.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_pow.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_rem_pio2.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_remainder.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_scalb.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_sinh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./e_sqrt.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./k_cos.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./k_sin.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./k_standard.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./k_tan.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_asinh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_atan.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_cbrt.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_ceil.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_copysign.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_cos.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_erf.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_expm1.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_fabs.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_finite.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_floor.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_frexp.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_ilogb.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_isnan.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_ldexp.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_log1p.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_logb.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_modf.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_nextafter.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_rint.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_scalbn.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_significand.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_sin.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_tan.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./s_tanh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_acos.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_acosh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_asin.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_atan2.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_atanh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_cosh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_exp.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_fmod.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_gamma.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_gamma_r.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_hypot.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_j0.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_j1.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_jn.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_lgamma.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_lgamma_r.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_log.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_log10.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_pow.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_remainder.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_scalb.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_sinh.bc stp 900 results_fdlibm_simple_stp.json
./run_bc_klee_fdlibm_simple.sh ./w_sqrt.bc stp 900 results_fdlibm_simple_stp.json
